description: Building your own fast, responsive, modern and minimalist start page

hb:
  header:
    socials:
      github: hbstack/theme-start
      paypal: razonyang
      kofi: razonyang
  theme_start:
    search_input_text: HB Framework
    # search_engines:
    #   google:
    #     weight: 1
    #   bing:
    #     weight: 2
    #   baidu:
    #     weight: 3
    #   duckduckgo:
    #     weight: 4
    #   wikipedia:
    #     disable: false
    #   yahoo:
    #     disable: false
    #   yandex:
    #     disable: false
    #   sogou:
    #     disable: false
